apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: gerrit
          artifact-id: 18e863e9-a106-421e-ab65-3447a8576a36
          target-environment: UAT